dataset:
  # support mode singlefile, multifile
  mode: multifile
  # the size of the image (X,X,3)
  image_shape: (512, 512, 3)
  # max number of objects that can be detected
  max_objects: 100
  # the size of the batch
  batch_size: 16
  anchors: 
    # anchors values: default, default_tiny, compute, path
    mode: default
   #the number of anchors can be 6 or 9, 12
    number: 9
    path: 
  images:
    pad_to_fixed_size: true

  annotations:
    # path of the annotations
    train:
    # path of the annotations for validation
    val:

  # if use data augmentation true or false
  augment: true
  
model:
  # The backbone for the model, default DarkNet, accepted values (ResNet50V2, ResNet101V2, ResNet152V2, DenseNet121, DenseNet169, DenseNet201, MobileNet, MobileNetV2)
  backbone: ResNet50V2
  # the training mode: transfer, fine_tune, train
  thresholds:
    intersection_over_union: 0.7
    object_score: 0.7
  reload:
    path:
  checkpoint:
    path: 
  
fit:
  #mode train, transfer, finetuning
  mode: finetuning
  epochs:
    transfer:
    finetuning:
    train:
  # number of the layers freezed for fine tuning it accepts positive and negate values (e.g. first 80 layers, last -10 layers)
  freezed_layers: -10
  run_eagerly: False
  optimizer:
    # sgd | rmsprop | adam ...
    name: rmsprop
    lrate:
      # cyclic | exp_range | reduce_on_plateau
      mode: reduce_on_plateau
      value: 0.0001




  